# ReadTheDocs build configuration for nimpulseqgui.
# Docs: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  # Full control over the build pipeline via commands.
  # Each command runs in a fresh shell; use absolute paths where needed.
  commands:
    # ---- 1. Install Nim via choosenim ----
    - curl -L https://nim-lang.org/choosenim/init.sh -sSf -o /tmp/choosenim_init.sh
    - sh /tmp/choosenim_init.sh -y stable
    # Verify installation
    - $HOME/.nimble/bin/nim --version

    # ---- 2. Install nimble dependencies ----
    - $HOME/.nimble/bin/nimble install nimpulseqgui -y

    # ---- 3. Install Python / Sphinx dependencies ----
    - pip install -r docs/requirements.txt

    # ---- 4. Generate RST from nim jsondoc ----
    - NIM=$HOME/.nimble/bin/nim python docs/generate_rst.py

    # ---- 5. Build Sphinx HTML ----
    - sphinx-build -T -b html docs/ $READTHEDOCS_OUTPUT/html/
